apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: csamatov-prod
spec:
  acme:
    email: fuchiropsolution@gmail.com
    privateKeySecretRef:
      name: csamatov-issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
          
          

